name: CD Prod All

on:
  workflow_dispatch:
    inputs:
      targetenv:
        description: 'Select Target Environment'     
        required: true
        default: 'test'
  schedule:
    - cron: '15 12 * * 1-5'
  
jobs:
  build:
    name: Run RP TEST 

    runs-on: [self-hosted, linux ]
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Build Tools
        run: |
          npm install -g yarn

      - name: Install dependecies
        run: yarn install

      - name: Run api tests
        run: yarn test

      - name: Publish Test Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reportApi.xml
          path: reports/reportApi.xml
          retention-days: 5
          
      - name: Post to Teams
        if: always()
        uses: ./.github-actions/notification
        with:
            teamsWebhookUrl: qaNotificationsWebhook
            message: ${{ github.workflow }} completed with Status - ${{ job.status }}  
